version: '3.8'

services:
  # MySQL
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: docker_bdd
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./flask_app/init_db.sql:/docker-entrypoint-initdb.d/init_db.sql

  # Flask
  web:
    build: ./flask_app
    container_name: flask_app
    ports:
      - "5000:5000"
    environment:
      - MYSQL_HOST=db
      - MYSQL_USER=root
      - MYSQL_PASSWORD=
      - MYSQL_DATABASE=docker_bdd
      - MYSQL_PORT=3306
    depends_on:
      - db
    volumes:
      - ./flask_app:/app

  # MongoDB
  mongo:
    image: mongo:6
    container_name: mongo_db
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  # Spring Boot
  spring:
    build: ./spring_app
    container_name: spring_app
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://mongo:27017/springdb
    depends_on:
      - mongo

volumes:
  db_data:
  mongo_data:
